using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OzelDersYonetim.Data;
using OzelDersYonetim.Models.Notifications;
using OzelDersYonetim.Models.ViewModels;
using OzelDersYonetim.Services.Auditing;
using OzelDersYonetim.Services.Notifications;
namespace OzelDersYonetim.Areas.Admin.Controllers;
[Area("Admin"),Authorize(Roles=IdentityDataSeeder.AdminRole)]
public class AnnouncementsController(ApplicationDbContext dbContext,IAnnouncementService service,AnnouncementFileService files,IAuditService audit):Controller
{
    public async Task<IActionResult> Index()=>View(await dbContext.Announcements.AsNoTracking().Include(x=>x.AnnouncementStudents).OrderByDescending(x=>x.PublishDate).ToListAsync());
    public async Task<IActionResult> Create()=>View(await FormAsync(new AnnouncementFormViewModel()));
    [HttpPost,ValidateAntiForgeryToken,RequestSizeLimit(25*1024*1024)]public async Task<IActionResult>Create(AnnouncementFormViewModel model){Validate(model);if(!ModelState.IsValid)return View(await FormAsync(model));try{await service.PublishAsync(model.Announcement,model.SelectedStudentIds);if(model.Attachment is not null){model.Announcement.AttachmentPath=await files.SaveAsync(model.Attachment);await dbContext.SaveChangesAsync();}}catch(InvalidOperationException ex){ModelState.AddModelError(string.Empty,ex.Message);return View(await FormAsync(model));}await audit.LogAsync("Duyuru yayınlama","Duyuru",model.Announcement.Id,model.Announcement.Title);TempData["Success"]="Duyuru yayınlandı ve bildirimler oluşturuldu.";return RedirectToAction(nameof(Index));}
    public async Task<IActionResult>Edit(int id){var item=await dbContext.Announcements.Include(x=>x.AnnouncementStudents).SingleOrDefaultAsync(x=>x.Id==id);if(item is null)return NotFound();return View(await FormAsync(new AnnouncementFormViewModel{Announcement=item,SelectedStudentIds=item.AnnouncementStudents.Select(x=>x.StudentProfileId).ToList()}));}
    [HttpPost,ValidateAntiForgeryToken,RequestSizeLimit(25*1024*1024)]public async Task<IActionResult>Edit(int id,AnnouncementFormViewModel model){if(id!=model.Announcement.Id)return BadRequest();Validate(model);if(!ModelState.IsValid)return View(await FormAsync(model));var item=await dbContext.Announcements.Include(x=>x.AnnouncementStudents).SingleOrDefaultAsync(x=>x.Id==id);if(item is null)return NotFound();var attachment=item.AttachmentPath;var created=item.CreatedAt;dbContext.Entry(item).CurrentValues.SetValues(model.Announcement);item.AttachmentPath=attachment;item.CreatedAt=created;item.UpdatedAt=DateTime.UtcNow;if(model.Attachment is not null)item.AttachmentPath=await files.SaveAsync(model.Attachment);var targetIds=await ResolveTargetIdsAsync(item,model.SelectedStudentIds);var existing=item.AnnouncementStudents.Select(x=>x.StudentProfileId).ToHashSet();dbContext.AnnouncementStudents.RemoveRange(item.AnnouncementStudents.Where(x=>!targetIds.Contains(x.StudentProfileId)));foreach(var studentId in targetIds.Except(existing))item.AnnouncementStudents.Add(new AnnouncementStudent{StudentProfileId=studentId});await dbContext.SaveChangesAsync();await audit.LogAsync("Duyuru güncelleme","Duyuru",id,item.Title);TempData["Success"]="Duyuru güncellendi.";return RedirectToAction(nameof(Index));}
    public async Task<IActionResult>Download(int id){var item=await dbContext.Announcements.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id);if(item?.AttachmentPath is null)return NotFound();var file=files.Open(item.AttachmentPath);return file is null?NotFound():File(file.Value.Stream,file.Value.ContentType,file.Value.FileName);}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Toggle(int id){var item=await dbContext.Announcements.FindAsync(id);if(item is null)return NotFound();item.IsActive=!item.IsActive;item.UpdatedAt=DateTime.UtcNow;await dbContext.SaveChangesAsync();await audit.LogAsync(item.IsActive?"Duyuru etkinleştirme":"Duyuru pasifleştirme","Duyuru",id,item.Title);TempData["Success"]=item.IsActive?"Duyuru etkinleştirildi.":"Duyuru pasifleştirildi.";return RedirectToAction(nameof(Index));}
    [HttpPost,ValidateAntiForgeryToken]public async Task<IActionResult>Delete(int id){var item=await dbContext.Announcements.FindAsync(id);if(item is null)return NotFound();item.IsActive=false;item.ExpiryDate=DateTime.Now;item.UpdatedAt=DateTime.UtcNow;await dbContext.SaveChangesAsync();await audit.LogAsync("Duyuru kaldırma","Duyuru",id,item.Title);TempData["Success"]="Duyuru yayından kaldırıldı; okuma geçmişi korundu.";return RedirectToAction(nameof(Index));}
    private void Validate(AnnouncementFormViewModel model){if(model.Announcement.ExpiryDate.HasValue&&model.Announcement.ExpiryDate<model.Announcement.PublishDate)ModelState.AddModelError("Announcement.ExpiryDate","Bitiş tarihi yayın tarihinden önce olamaz.");if(model.Announcement.TargetType==AnnouncementTargetType.SelectedStudents&&model.SelectedStudentIds.Count==0)ModelState.AddModelError(nameof(model.SelectedStudentIds),"En az bir öğrenci seçin.");if(model.Announcement.TargetType==AnnouncementTargetType.GradeLevel&&string.IsNullOrWhiteSpace(model.Announcement.GradeLevel))ModelState.AddModelError("Announcement.GradeLevel","Hedef sınıf zorunludur.");}
    private async Task<HashSet<int>>ResolveTargetIdsAsync(Announcement item,IReadOnlyCollection<int> selected)=>item.TargetType switch{AnnouncementTargetType.SelectedStudents=>selected.ToHashSet(),AnnouncementTargetType.GradeLevel=>(await dbContext.StudentProfiles.Where(x=>x.IsActive&&x.GradeLevel==item.GradeLevel).Select(x=>x.Id).ToListAsync()).ToHashSet(),_=>(await dbContext.StudentProfiles.Where(x=>x.IsActive).Select(x=>x.Id).ToListAsync()).ToHashSet()};
    private async Task<AnnouncementFormViewModel>FormAsync(AnnouncementFormViewModel model){model.Students=await dbContext.StudentProfiles.Where(x=>x.IsActive).OrderBy(x=>x.FirstName).Select(x=>new SelectListItem(x.FullName+" · "+x.GradeLevel,x.Id.ToString())).ToListAsync();return model;}
}
